vich_uploader:
    db_driver: orm

    metadata:
       type: attribute

    mappings:
       image_pays:
           uri_prefix: /image/pays
           upload_destination: '%kernel.project_dir%/public/image/pays'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
